### ISSUE TITLE
Remove Hello World Intent

### ISSUE THREAD

**Issue by erikfuego** [codeherk/hOOt#12]
Should we remove the Hello World intent? This intent was apart of a template and we no longer need it.

**Comment by codeherk** [comment]
Yes, it should be removed. I left the intent there during the project so that if any issues occur with our **custom intents**, we would have the template intent to test to confirm that our Alexa skill is somewhat working. I will remove it.

**Comment by codeherk** [comment]
Closing this issue since intent is now removed.
