### ISSUE TITLE
Retrieving Assignments by course name instead of position

### ISSUE THREAD

**Issue by codeherk** [codeherk/hOOt#3]
Alexa says "What position" in relation to course array index when I ask for "What assignments do I have?".

**As a** user, **I want** Alexa to ask me the **name of the class** I am requesting assignments from and **confirm** the course it matched it to **so that** what course I am getting assignments from. 

There is a package called js-levenshtein, that easily implements the Levenshtein distance algorithm. This algorithm could be used to check if the course name the user told Alexa matches any of the course names return from Canvas' API.

The Assignment Intent Handler would need to be updated and the **en-US.json** file would need to include phrases for the Intent and Dialog.

**Comment by leekd99** [comment]
Successfully implemented Levenshtein algorithm to match user request to correct course.
Algorithm has been integrated into Alexa intent handler to to take user's request and give Alexa the appropriate course info to fetch the assignments for that course.
